spring.application.name=DulceControl
spring.datasource.url=jdbc:postgresql://localhost:5432/dulcecontrol
spring.datasource.username=${POSTGRE_DB_USER:postgres}
spring.datasource.password=${POSTGRE_DB_PASSWORD}

spring.flyway.enabled=true