export const METODOS_PAGO = {
    EFECTIVO: 'EFECTIVO',
    YAPE: 'YAPE',
    PLIN: 'PLIN',
    TARJETA_CREDITO: 'TARJETA_CREDITO',
    TARJETA_DEBITO: 'TARJETA_DEBITO',
    TRANSFERENCIA: 'TRANSFERENCIA',
    PASARELA_ONLINE: 'PASARELA_ONLINE',
};

export const ESTADOS_PEDIDO = {
    BORRADOR: 'BORRADOR',
    PENDIENTE_PAGO: 'PENDIENTE_PAGO',
    PAGADO: 'PAGADO',
    EN_PREPARACION: 'EN_PREPARACION',
    LISTO_ENTREGA: 'LISTO_ENTREGA',
    ENTREGADO: 'ENTREGADO',
    CANCELADO: 'CANCELADO',
    DEVUELTO: 'DEVUELTO',
};

export const TIPOS_ENTREGA = {
    RECOJO_TIENDA: 'recojo_tienda',
    DELIVERY: 'delivery',
    CONSUMO_LOCAL: 'consumo_local',
};

export const ESTADOS_PAGO = {
    PENDIENTE: 'PENDIENTE',
    PARCIAL: 'PARCIAL',
    PAGADO_TOTAL: 'PAGADO_TOTAL',
    REEMBOLSADO: 'REEMBOLSADO',
};
